### ISSUE TITLE
"The set with the given name does not exist"

### ISSUE THREAD

**Issue by donmega** [terrabyte911/bash-iptables-country-block#1]
Hi,

When running your script, i am getting the following error right after running it:

ipset v7.15: The set with the given name does not exist
ipset v7.15: The set with the given name does not exist

Downloading Country Zone: cn.zone

Downloading Country Zone: ru.zone

etc. etc.

**Comment by terrabyte911** [comment]
Hi, on the first run this is normal as ipset is trying to flush and destroy the blockall set that has not actually been created yet.
Run the script a second time and the messages will disappear.
I have altered the script to suppress these messages.

You can check all the ip's are in the set with the command `ipset list blockall -terse`

Name: blockall
Type: hash:net
Revision: 6
Header: family inet hashsize 8192 maxelem 65536
Size in memory: 512360
References: 1
Number of entries: 18692

18692 ip entries
1 reference is the iptables rule

To view every ip in the set use `ipset list blockall`

All the best.
Terra.

**Comment by donmega** [comment]
You are right! Seems to be working great. Thank you very much!
